DEBUG_FLAGS=
DEBUG_FLAGS="${DEBUG_FLAGS} -debug"
DEBUG_FLAGS="${DEBUG_FLAGS} -state"
DEBUG_FLAGS="${DEBUG_FLAGS} -msg"
DEBUG_FLAGS="${DEBUG_FLAGS} -tlsextdebug"

CIPHERS=
CIPHERS="${CIPHERS}:ECDHE-ECDSA-AES256-SHA"
CIPHERS="${CIPHERS}:ECDHE-ECDSA-AES128-GCM-SHA256"

#PORT=4444
# use UDP proxy
# PORT=12345
PORT=5684

openssl s_client \
	-dtls1_2 \
	-connect 127.0.0.1:${PORT} \
	${DEBUG_FLAGS} \
	-cipher ${CIPHERS}
